package com.bugtsa.iceandfire.data.storage.models;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHARACTERS".
*/
public class CharacterOfHouseDao extends AbstractDao<CharacterOfHouse, Long> {

    public static final String TABLENAME = "CHARACTERS";

    /**
     * Properties of entity CharacterOfHouse.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RemoteId = new Property(1, String.class, "remoteId", false, "REMOTE_ID");
        public final static Property HouseRemoteId = new Property(2, String.class, "houseRemoteId", false, "HOUSE_REMOTE_ID");
        public final static Property Url = new Property(3, String.class, "url", false, "URL");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Gender = new Property(5, String.class, "gender", false, "GENDER");
        public final static Property Culture = new Property(6, String.class, "culture", false, "CULTURE");
        public final static Property Born = new Property(7, String.class, "born", false, "BORN");
        public final static Property Died = new Property(8, String.class, "died", false, "DIED");
        public final static Property Father = new Property(9, String.class, "father", false, "FATHER");
        public final static Property Mother = new Property(10, String.class, "mother", false, "MOTHER");
        public final static Property Spouse = new Property(11, String.class, "spouse", false, "SPOUSE");
        public final static Property Alias = new Property(12, String.class, "alias", false, "ALIAS");
    };

    private DaoSession daoSession;

    private Query<CharacterOfHouse> house_MCharacterOfHousesQuery;

    public CharacterOfHouseDao(DaoConfig config) {
        super(config);
    }
    
    public CharacterOfHouseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHARACTERS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"REMOTE_ID\" TEXT," + // 1: remoteId
                "\"HOUSE_REMOTE_ID\" TEXT," + // 2: houseRemoteId
                "\"URL\" TEXT," + // 3: url
                "\"NAME\" TEXT," + // 4: name
                "\"GENDER\" TEXT," + // 5: gender
                "\"CULTURE\" TEXT," + // 6: culture
                "\"BORN\" TEXT," + // 7: born
                "\"DIED\" TEXT," + // 8: died
                "\"FATHER\" TEXT," + // 9: father
                "\"MOTHER\" TEXT," + // 10: mother
                "\"SPOUSE\" TEXT," + // 11: spouse
                "\"ALIAS\" TEXT);"); // 12: alias
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHARACTERS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CharacterOfHouse entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String remoteId = entity.getRemoteId();
        if (remoteId != null) {
            stmt.bindString(2, remoteId);
        }
 
        String houseRemoteId = entity.getHouseRemoteId();
        if (houseRemoteId != null) {
            stmt.bindString(3, houseRemoteId);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(4, url);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
 
        String culture = entity.getCulture();
        if (culture != null) {
            stmt.bindString(7, culture);
        }
 
        String born = entity.getBorn();
        if (born != null) {
            stmt.bindString(8, born);
        }
 
        String died = entity.getDied();
        if (died != null) {
            stmt.bindString(9, died);
        }
 
        String father = entity.getFather();
        if (father != null) {
            stmt.bindString(10, father);
        }
 
        String mother = entity.getMother();
        if (mother != null) {
            stmt.bindString(11, mother);
        }
 
        String spouse = entity.getSpouse();
        if (spouse != null) {
            stmt.bindString(12, spouse);
        }
 
        String alias = entity.getAlias();
        if (alias != null) {
            stmt.bindString(13, alias);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CharacterOfHouse entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String remoteId = entity.getRemoteId();
        if (remoteId != null) {
            stmt.bindString(2, remoteId);
        }
 
        String houseRemoteId = entity.getHouseRemoteId();
        if (houseRemoteId != null) {
            stmt.bindString(3, houseRemoteId);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(4, url);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
 
        String culture = entity.getCulture();
        if (culture != null) {
            stmt.bindString(7, culture);
        }
 
        String born = entity.getBorn();
        if (born != null) {
            stmt.bindString(8, born);
        }
 
        String died = entity.getDied();
        if (died != null) {
            stmt.bindString(9, died);
        }
 
        String father = entity.getFather();
        if (father != null) {
            stmt.bindString(10, father);
        }
 
        String mother = entity.getMother();
        if (mother != null) {
            stmt.bindString(11, mother);
        }
 
        String spouse = entity.getSpouse();
        if (spouse != null) {
            stmt.bindString(12, spouse);
        }
 
        String alias = entity.getAlias();
        if (alias != null) {
            stmt.bindString(13, alias);
        }
    }

    @Override
    protected final void attachEntity(CharacterOfHouse entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CharacterOfHouse readEntity(Cursor cursor, int offset) {
        CharacterOfHouse entity = new CharacterOfHouse( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // remoteId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // houseRemoteId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // url
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // gender
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // culture
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // born
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // died
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // father
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // mother
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // spouse
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // alias
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CharacterOfHouse entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRemoteId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHouseRemoteId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGender(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCulture(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBorn(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDied(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFather(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMother(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSpouse(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setAlias(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CharacterOfHouse entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CharacterOfHouse entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "mCharacterOfHouses" to-many relationship of House. */
    public List<CharacterOfHouse> _queryHouse_MCharacterOfHouses(String houseRemoteId) {
        synchronized (this) {
            if (house_MCharacterOfHousesQuery == null) {
                QueryBuilder<CharacterOfHouse> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.HouseRemoteId.eq(null));
                house_MCharacterOfHousesQuery = queryBuilder.build();
            }
        }
        Query<CharacterOfHouse> query = house_MCharacterOfHousesQuery.forCurrentThread();
        query.setParameter(0, houseRemoteId);
        return query.list();
    }

}
