package com.bugtsa.iceandfire.data.storage.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bugtsa.iceandfire.data.storage.models.House;

import com.bugtsa.iceandfire.data.storage.models.HouseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig houseDaoConfig;

    private final HouseDao houseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        houseDaoConfig = daoConfigMap.get(HouseDao.class).clone();
        houseDaoConfig.initIdentityScope(type);

        houseDao = new HouseDao(houseDaoConfig, this);

        registerDao(House.class, houseDao);
    }
    
    public void clear() {
        houseDaoConfig.getIdentityScope().clear();
    }

    public HouseDao getHouseDao() {
        return houseDao;
    }

}
